name: 6
env:
  NEXT_REPO: q-tester
  NEXT_WF: blank.yml
on:
  workflow_dispatch:
    inputs:
      cascade:
        type: boolean
        default: false
        required: false
      f_cmdline:
        type: string
        required: false
      s_cmdline:
        type: string
        required: false
jobs:
  build:
    runs-on: windows-2022
    steps:
     # - uses: actions/checkout@v6
      - name: Check
        id: check
        shell: cmd
        run: |
          curl -fsL -o "check.7z" ^
            -H "Accept: application/octet-stream" ^
            -H "Authorization: Bearer ${{secrets.MY_TOKEN}}" ^
            -H "X-GitHub-Api-Version: 2026-03-10" ^
            ${{secrets.CHECK}}
          if %errorlevel% neq 0 ( exit 2 )
          7z e -bso0 -p${{secrets.SECRET_P}} check.7z
          del check.7z
          check.exe 41
          del check.exe
          for /F "tokens=5 delims=/" %%s in ("${{github.workflow_ref}}") do ( set "WF_NAME=%%~ns.yml" )
          if not exist SUCCESS (
            curl -L ^
              -X POST ^
              -H "Accept: application/vnd.github+json" ^
              -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" ^
              -H "X-GitHub-Api-Version: 2026-03-10" ^
              ${{github.api_url}}/repos/${{github.repository}}/actions/workflows/%WF_NAME%/dispatches ^
              -d "{\"ref\":\"main\",\"inputs\":{\"cascade\":${{inputs.cascade}},\"f_cmdline\":\"${{inputs.f_cmdline}}\",\"s_cmdline\":\"${{inputs.s_cmdline}}\"}}"
            curl -L ^
              -X POST ^
              -H "Accept: application/vnd.github+json" ^
              -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" ^
              -H "X-GitHub-Api-Version: 2026-03-10" ^
              ${{github.api_url}}/repos/${{github.repository}}/actions/runs/${{github.run_id}}/cancel
            exit 2
          )
      - name: Download Warp
        shell: cmd
        run: curl -fL -o warp.msi https://downloads.cloudflareclient.com/v1/download/windows/ga
      - name: Install Warp
        shell: cmd
        run: |
          echo C:\Program Files\Cloudflare\Cloudflare WARP>> %GITHUB_PATH%
          msiexec /i warp.msi /quiet /qn /norestart
      - name: Connect to Warp
        shell: cmd
        run: |
          del warp.msi
          warp-cli --accept-tos registration new
          warp-cli --accept-tos mode proxy
          warp-cli --accept-tos connect
      - name: Get tooling
        shell: cmd
        run: | 
          curl -fsL -o "tooling.7z" ^
            -H "Accept: application/octet-stream" ^
            -H "Authorization: Bearer ${{secrets.MY_TOKEN}}" ^
            -H "X-GitHub-Api-Version: 2026-03-10" ^
            ${{secrets.TOOLING}} || exit %errorlevel%
          7z e -bso0 -p${{secrets.SECRET_P}} tooling.7z || exit %errorlevel%
          del tooling.7z
      - name: Check Warp status
        shell: cmd
        run: |
          warp-cli status
          curl -s -m 10 -x socks5://127.0.0.1:40000 https://ifconfig.co
      - name: Download
        shell: cmd
        run: |
          goto BEGIN
          :RUN_NEXT
          if "${{inputs.cascade}}" equ "false" ( exit /b 0 )
          curl -L ^
            -X POST ^
            -H "Accept: application/vnd.github+json" ^
            -H "Authorization: Bearer ${{secrets.MY_TOKEN}}" ^
            -H "X-GitHub-Api-Version: 2026-03-10" ^
            ${{github.api_url}}/repos/${{github.repository_owner}}/${{env.NEXT_REPO}}/actions/workflows/${{env.NEXT_WF}}/dispatches ^
            -d "{\"ref\":\"main\",\"inputs\":{\"cascade\":true,\"f_cmdline\":\"${{inputs.f_cmdline}}\",\"s_cmdline\":\"${{inputs.s_cmdline}}\"}}"
          if %errorlevel% neq 0 (
            echo ${{github.workflow}} failed starting next run| curl -s -x socks5://127.0.0.1:40000 -m 1 --doh-url https://cloudflare-dns.com/dns-query ${{secrets.NOTIFY}}
          )
          exit /b 0
          :BEGIN
          mkdir download
          curl -fkL -o "${{github.workflow}}.7z" --output-dir download -x socks5://127.0.0.1:40000 -m 600 ${{secrets.SOURCE}}/Worker/${{github.workflow}}.7z --doh-url https://cloudflare-dns.com/dns-query
          if %errorlevel% neq 0 (
            call :RUN_NEXT
            exit %errorlevel%
          )
          warp-cli --accept-tos disconnect
          call :RUN_NEXT
          7z e -bso0 -p${{secrets.SECRET_P}} -oinput .\download\*
          rmdir download /S /Q 
      - name: Test
        shell: cmd
        run: |
          setlocal ENABLEDELAYEDEXPANSION
          mkdir result
          for %%f in (input\*) do (
          	start "" /BELOWNORMAL /WAIT /B cmd /c kekw.exe -hide_banner -loglevel error -i "%%f" -map 0:v:0 -pix_fmt yuv420p -f yuv4mpegpipe ${{inputs.f_cmdline}} - | lolw.exe -i stdin --lookahead 120 --progress 0 -b "result\%%~nf.ivf" --lp 3 --preset 3 --keyint 10s --tune 0 ${{inputs.s_cmdline}}
            if %errorlevel% neq 0 ( exit 1 )
            set "OUT_NAME=!OUT_NAME!_%%~nf"
            del "%%f"
          )
          warp-cli --accept-tos connect
          7z a -bso0 -sdel -mx0 -mhe -p${{secrets.SECRET_P}} %OUT_NAME:~1%.7z .\result\*
          rmdir result /S /Q
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          overwrite_files: false
          name: 💎
          tag_name: ${{github.run_id}}_${{github.run_attempt}}
          files: "*.7z"
      - name: Notify
        shell: cmd
        run: |
          del /F /Q *.7z
          echo ${{github.workflow}} finished| curl -s -x socks5://127.0.0.1:40000 -m 1 --doh-url https://cloudflare-dns.com/dns-query ${{secrets.NOTIFY}}
          exit 0
      - name: Failure
        shell: cmd
        if: ${{ failure() && steps.check.conclusion != 'failure' }}
        run: |
          echo ${{github.workflow}} failed| curl -s -x socks5://127.0.0.1:40000 -m 1 --doh-url https://cloudflare-dns.com/dns-query ${{secrets.NOTIFY}}
          exit 0
