name: 6
env:
  THIS_WF: ${{github.workflow}}
  NEXT_REPO: q-tester
  NEXT_WF: blank.yml
on:
  workflow_dispatch:
    inputs:
      cascade:
        type: boolean
        default: false
        required: false
      f_cmdline:
        type: string
        required: false
      s_cmdline:
        type: string
        required: false
jobs:
  build:
    runs-on: windows-latest
    steps:
      # - uses: actions/checkout@v6
      - name: Prepare
        shell: cmd
        run: |
          goto BEGIN
          :RUN_NEXT
          if "${{inputs.cascade}}" equ "false" ( exit /b 0 )
          curl -L ^
            -X POST ^
            -H "Accept: application/vnd.github+json" ^
            -H "Authorization: Bearer ${{secrets.MY_TOKEN}}" ^
            -H "X-GitHub-Api-Version: 2026-03-10" ^
            ${{github.api_url}}/repos/${{github.repository_owner}}/${{env.NEXT_REPO}}/actions/workflows/${{env.NEXT_WF}}/dispatches ^
            -d "{\"ref\":\"main\",\"inputs\":{\"cascade\":true,\"f_cmdline\":\"${{inputs.f_cmdline}}\",\"s_cmdline\":\"${{inputs.s_cmdline}}\"}}"
          exit /b 0
          :BEGIN
          winget install Cloudflare.Warp --accept-source-agreements --accept-package-agreements --disable-interactivity --silent
          set "PATH=%PATH%;C:\Program Files\Cloudflare\Cloudflare WARP"
          warp-cli --accept-tos registration new
          warp-cli --accept-tos mode proxy
          warp-cli --accept-tos connect
          curl -fsL -o "tooling.7z" ^
            -H "Accept: application/octet-stream" ^
            -H "Authorization: Bearer ${{secrets.MY_TOKEN}}" ^
            -H "X-GitHub-Api-Version: 2026-03-10" ^
            ${{secrets.TOOLING}}
          if %errorlevel% neq 0 (
            echo %THIS_WF% failed| curl -s -x socks5://127.0.0.1:40000 -m 1 ${{secrets.NOTIFY}}
            exit 1
          )
          7z e -bso0 -p${{secrets.SECRET_P}} tooling.7z
          del tooling.7z
          warp-cli status
          curl -s -m 10 -x socks5://127.0.0.1:40000 https://ifconfig.co
          mkdir download
          curl -fkL -o "%THIS_WF%.7z" --output-dir download -x socks5://127.0.0.1:40000 -m 300 ${{secrets.SOURCE}}/Worker/%THIS_WF%.7z
          if %errorlevel% neq 0 (
            echo %THIS_WF% failed| curl -s -x socks5://127.0.0.1:40000 -m 1 ${{secrets.NOTIFY}}
            call :RUN_NEXT
            exit 1 
          )
          warp-cli --accept-tos disconnect
          call :RUN_NEXT
          7z e -bso0 -p${{secrets.SECRET_P}} -oinput .\download\*
          rmdir download /S /Q 
      - name: Test
        shell: cmd
        run: |
          mkdir result
          for %%f in (input\*) do (
          	kekw.exe -hide_banner -loglevel error -i "%%f" -map 0:v:0 -pix_fmt yuv420p -f yuv4mpegpipe ${{inputs.f_cmdline}} - | lolw.exe -i stdin --lookahead 120 --progress 0 -b "result\%%~nf.ivf" --lp 3 --preset 3 --keyint 10s --tune 0 ${{inputs.s_cmdline}}
            del "%%f"
          )
          set "PATH=%PATH%;C:\Program Files\Cloudflare\Cloudflare WARP"
          warp-cli --accept-tos connect
          7z a -bso0 -sdel -mx0 -mhe -p${{secrets.SECRET_P}} release%THIS_WF%.7z .\result\*
          rmdir result /S /Q
      - name: Finish
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: latest
          draft: true
          files: release${{env.THIS_WF}}.7z
      - name: Notify
        shell: cmd
        run: |
          del release${{env.THIS_WF}}.7z
          echo %THIS_WF% finished| curl -s -x socks5://127.0.0.1:40000 -m 1 ${{secrets.NOTIFY}}
          exit 0
